# Generated by Django 4.2.3 on 2026-02-03 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0002_alter_choice_id_alter_course_id_alter_enrollment_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='choice_text',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='question_text',
            new_name='content',
        ),
        migrations.AlterField(
            model_name='question',
            name='grade',
            field=models.IntegerField(default=50),
        ),
    ]
